on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ 20 ]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'

      - name: Run Npm:ci
        run: npm ci

      - name: Run Npm:format
        run: npm run format

      - name: Run Npm:lint
        run: npm run lint

      - name: Run Npm:test
        run: npm run test
